// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmsikhszbbqcboppdufa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxtc2lraHN6YmJxY2JvcHBkdWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzY0NTYsImV4cCI6MjA3MzcxMjQ1Nn0.2z3mavhr4YqEMFrKSwCd9NJrZyYtzEdTCGscYKVYWwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});